# frozen_string_literal: true

source "https://rubygems.org"

gem "rake-compiler"
gem "rake", "~> 13.0"

%w[rspec rspec-core rspec-expectations rspec-mocks rspec-support].each do |lib|
  if lib == 'rspec'
    gem lib, git: "https://github.com/rspec/rspec"
  else
    gem lib, git: "https://github.com/rspec/rspec", glob: "#{lib}/#{lib}.gemspec"
  end
end
